test_file = open("airtrafficcontroller.txt", "w")
test_file.write("Daly City, CA")
test_file.write("God has a plan for me")
test_file.write("Rich people")
test_file.write("Santa Clara")
print("What is your name")
name = input()
test_file.write("your name is ", name)
test_file.close()